### ISSUE TITLE
Serializing fixed sized arrays

### ISSUE THREAD

**Issue by mikhailOK** [near/borsh#36]
After #33 borsh can serialize fixed sized arrays of any type, but deserialize only byte arrays.
That's inconsistent

**Comment by nearmax** [comment]
Since there is no trait specialization available in stable Rust we should only implement serializer/deserializer for standard types. So the solution to this issue is to remove serialization of non-primitive arrays and add serializers for primitive arrays.

We should also further investigate how bincode and serder address this issue. Assigning to @fckt

**Comment by jsoneaday** [comment]
Do you guys have a sample of deserializing an array of some type?

**Comment by nonergodic** [comment]
Any update on this?

**Comment by nonergodic** [comment]
Hah, just read the code and found that it was actually implemented with 0.9.1 release... i.e. 6 days ago!

just had to update my cargo.toml dependency to:
`borsh = { version = "0.9.1", features = ["const-generics"] }`
and now things work ❤️

**Comment by bowenwang1996** [comment]
So looks like this can be closed
